# Generated by Django 2.1.1 on 2018-09-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_course_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='courses_title', to='api.Course'),
        ),
    ]
