export const FETCH_DATA = '@@MAIN_PAGE/FETCH_DATA';
export const FETCH_DATA_SUCCESS = '@@MAIN_PAGE/FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = '@@MAIN_PAGE/FETCH_DATA_FAILURE';

export default {

}